Update auto-sync-fork.yml

diff --git a/.github/workflows/auto-sync-fork.yml b/.github/workflows/auto-sync-fork.yml
--- a/.github/workflows/auto-sync-fork.yml
+++ b/.github/workflows/auto-sync-fork.yml
@@ -3,7 +3,7 @@ name: Auto Sync Fork with Upstream
 on:
   workflow_dispatch:
   schedule:
-    - cron: '*/5 * * * *' # Run every 5 minutes
+    - cron: '0 0 * * 5' # Schedule to run every Friday at midnight UTC
 
 jobs:
   sync:
@@ -11,31 +11,29 @@ jobs:
 
     steps:
     - name: Sync forked repo
-      run: gh repo sync SasithonS/appsmith_mirror -b release
+      run: gh repo sync SasithonS/appsmith_mirror -b release ||  echo "Sync Failed." && exit 1
       env:
         GITHUB_TOKEN: ${{ secrets.ST_WORKFLOW_PAT }}
-  # job:
-  # sync:
-  #   runs-on: ubuntu-latest
-
-  #   steps:
-  #   - name: Checkout Repository
-  #     uses: actions/checkout@v2
       
-  #   - name: Configure Git User
-  #     run: |
-  #       git config user.name "${{ secrets.GIT_USER_NAME }}"
-  #       git config user.email "${{ secrets.GIT_USER_EMAIL }}"
-            
-  #   - name: Set Upstream Remote
-  #     run: git remote add upstream https://github.com/SasithonSS/appsmith_mirror.git
-  #     # Replace "https://github.com/original/repo.git" with the URL of the upstream repository.
-
-  #   - name: Fetch Upstream Changes
-  #     run: git fetch upstream
-
-  #   - name: Merge Upstream Changes
-  #     run: git merge upstream/release --allow-unrelated-histories # Replace "main" with the branch you want to sync
-
-  #   - name: Push Changes to Fork
-  #     run: git push origin release # Replace "main" with the branch you want to sync
+    - name: Get Current UTC Time
+      if: ${{ success() }} # This step will only execute if the merge step success.
+      id: current_time
+      run: |
+        current_time=$(date -u +"%d-%m-%Y-%H%M%S")
+        current_date=$(date -u +"%d-%m-%Y")
+        echo "::set-output name=utc_time::$current_time"
+        echo "::set-output name=pr_date::$current_date"
+        
+    - name: Create Pull Request
+      if: ${{ success() }} # This step will only execute if the merge step success.
+      run: |
+        pr_title=" Pull Request from release to dev ${{ steps.current_time.outputs.utc_time }}"
+        pr_body="This pull request was automatically created at ${{ steps.current_time.outputs.pr_date }}"
+        curl -X POST -H "Authorization: token ${{ secrets.ST_WORKFLOW_PAT }}" \
+            -d '{
+              "title": "'"$pr_title"'",
+              "body": "'"$pr_body"'",
+              "head": "release",
+              "base": "dev"
+            }' \
+              "https://api.github.com/repos/${{ github.repository }}/pulls"
